export const WELCOME_HAS_ERRORED = 'WELCOME_HAS_ERRORED';
export const WELCOME_IS_LOADING = 'WELCOME_IS_LOADING';
export const WELCOME_FETCH_DATA_SUCCESS = 'WELCOME_FETCH_DATA_SUCCESS';

export const SOCIAL_NETWORKS_HAS_ERRORED = 'SOCIAL_NETWORKS_HAS_ERRORED';
export const SOCIAL_NETWORKS_IS_LOADING = 'SOCIAL_NETWORKS_IS_LOADING';
export const SOCIAL_NETWORKS_FETCH_DATA_SUCCESS = 'SOCIAL_NETWORKS_FETCH_DATA_SUCCESS';
